on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/env-export
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
          DEMO_PASSWORD: secrethub://florisvdg/demo/password
          SLACK_WEBHOOK: secrethub://florisvdg/demo/slack_webhook
      - name: Print environment with masked secrets
        run: env
      - name: Notify Slack
        uses: Ilshidur/action-slack@master # this Action expects SLACK_WEBHOOK to be set
        with:
          args: Hello from GitHub Actions 🚀
