on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/env-export
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
          DEMO_PASSWORD: secrethub://florisvdg/demo/password
      - name: Test my app
        run: |
          echo "Password $DEMO_PASSWORD"
